name: CSHARP CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 1

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.502

      - name: Build
        run: dotnet build src/Qiniu/Qiniu.csproj
      
      - name: Test
        run: |
          export QINIU_ACCESS_KEY=qhtbC5YmDCO-WiPriuoCG_t4hZ1LboSOtRYSJXo_
          export QINIU_SECRET_KEY=3sSWVQQ_HvD6pVJSjfEsRQMl9ZRnNRf0-G5iomNV
          export QINIU_TEST_BUCKET=z0-bucket
          export QINIU_TEST_DOMAIN=http://up.qiniup.com
          dotnet build src/Qiniu/Qiniu.csproj
        
      - name: After_success
        run: bash <(curl -s https://codecov.io/bash)